/// Generated by AssetsRefGenerator on 2020/11/05
class Res {
  static const String delivery = "images/delivery.png";
  static const String eat = "images/eat.png";
  static const String fd = "images/fd.png";
  static const String logo = "images/logo.png";
}
